config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :about, only: [:index]
  resources :video_games, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  resources :publishers, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  resources :developers, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  resources :platforms, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/developer.rb
class Developer < ApplicationRecord
    has_many :video_games
    validates :name, presence: true, uniqueness: true
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :video_games
    validates :name, presence: true, uniqueness: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :video_games
    validates :name, presence: true, uniqueness: true
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  belongs_to :publisher
  belongs_to :developer
  belongs_to :platform

  validates :name, :release_date, :summary, :meta_score, :review, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @developers = Developer.all
  end

  def show
    @developer = Developer.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @developers = Developer.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @video_games = VideoGame.includes(:developer)
                            .order("metacritic_score DESC")
                            .limit(25)
    @publishers = Publisher.limit(10)
    @developers = Developer.limit(10)
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @platforms = Platform.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.all
  end

  def show
    @publisher = Publisher.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @publishers = Publisher.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  def index
    @video_games = VideoGame.all
  end

  def show
    @video_game = VideoGame.find(params[:id])
    @developer = Developer.joins(:video_games).where("video_games.id = ?", params[:id]).first
    @publisher = Publisher.joins(:video_games).where("video_games.id = ?", params[:id]).first
    @platform = Platform.joins(:video_games).where("video_games.id = ?", params[:id]).first
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @video_games = VideoGame.where("name LIKE ?", wildcard_search)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/about/index.html.erb
<% content_for(:html_title) {"About this Project"}%>
<br>
<p>This website is the end creation of a project for the Full Stack Web Development course at Red River Collegiate Polytechnic.</p>
<br>
<p>The data used for this website is a subset of the <a href="https://www.kaggle.com/datasets/deepcontractor/top-video-games-19952021-metacritic/data">data source found here.</a></p>
<p>The data is organized into name, platforms, release date, summary, meta_score, and user_review columns containing strings, text, dates, decimals, etc.</p>
<p>Alongside that data, I added the publishers and developers for the respective game to be added into separate tables.</p>
<p>I sorted the data into four separate tables. The <b>video games table</b>, containing a majority of the data, and a table for <b>developers</b>, <b>publishers</b>, and <b>platforms</b>, containing their name.</p>
<br>
<p>This is an ERD (Entity Relationship Diagram) of the database used for this website.</p>
<%= image_tag("ERDDiagram.png", :alt => "ERD Diagram for the database", :size => "500")%>

app/views/developers/index.html.erb
<% content_for(:html_title) {"Developers"}%>

<ul>
    <% @developers.each do |d| %>
    <li>
        <%= link_to d.name, d %>
    </li>
    <% end%>
</ul>

app/views/developers/search.html.erb
<p class="mb-5">
    Found <%= pluralize(@developers.count, 'developer') %> when searching for: <%= params[:keywords] %>
</p>
<div class="columns is-multiline">
    <% @developers.each do |d| %>
    <div class="column is-one-quarter">
        <div>
        <%= link_to "#{d.name}", d %>
        </div>
    </div>
    <% end %>
</div>

app/views/developers/show.html.erb
<% content_for(:html_title) {raw @developer.name}%>
<br>
<h4 class="subtitle is-4">Games developed by <%= @developer.name%>:</h4>

<div class="columns is-multiline">
    <% @developer.video_games.each do |vg| %>
        <div class="column is-one-quarter">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "300")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>


<a href="/developers"><b>Return to all developers</b></a>

app/views/home/index.html.erb
<div class="columns">
    <div class="column">
        <h2 class="title is-2">Top 25 Games</h2>
        <ol>
            <% @video_games.each do |vg| %>
            <li>
                <%= link_to vg.name, vg%>
                <em>
                    (<%= "#{vg.metacritic_score}"%>)
                </em>
            </li>
            <% end %>
        </ol>
        <p>
            <strong><%= link_to "See all the top 200 games.", video_games_path%> </strong>
        </p>
    </div>
    <div class="column">
        <h2 class="title is-2">10 Developers of Top Games</h2>
        <ol>
            <% @developers.each do |d| %>
            <li>
                <%= link_to d.name, d%>
            </li>
            <% end %>
        </ol>
        <p>
            <strong><%= link_to "See all the developers of top games.", developers_path%></strong>
        </p>
    </div>
    <div class="column">
        <h2 class="title is-2">10 Publishers of Top Games</h2>
        <ol>
            <% @publishers.each do |d| %>
            <li>
                <%= link_to d.name, d%>
            </li>
            <% end %>
        </ol>
        <p>
            <strong><%= link_to "See all the publishers of top games.", publishers_path%></strong>
        </p>
    </div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar">
    <div class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/">Home</a>
            <a class="navbar-item" href="/about">About</a>
            <a class="navbar-item" href="/video_games">Video Games</a>
            <a class="navbar-item" href="/developers">Developers</a>
            <a class="navbar-item" href="/publishers">Publishers</a>
            <a class="navbar-item" href="/platforms">Platforms</a>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Metacritic's Top 200ish Games</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= render "layouts/menu" %>
    <section class="section">
      <div class="container">
        <h1 class="title is-1">Top 200ish Games<%= " - " + yield(:html_title) if content_for?(:html_title)%></h1>
      </div>
      <br>

      <%= form_with(url: params[:type], method: :get, local: true) do |form| %>
        <div class="field is-grouped mb-5">
          <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Enter a search query...") %>
          </div>
          <div class="control">
            <%= form.select :type, [["Video Games", search_video_games_path], ["Developers", search_developers_path], ["Publishers", search_publishers_path], ["Platforms", search_platforms_path]] %>
          </div>
          <div class="control">
            <%= submit_tag("Search", class:"button is-primary") %>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </section>
  </body>
</html>

app/views/platforms/index.html.erb
<% content_for(:html_title) {"Platforms"}%>

<ul>
    <% @platforms.each do |p| %>
    <li>
        <%= link_to p.name, p %>
    </li>
    <% end%>
</ul>

app/views/platforms/search.html.erb
<p class="mb-5">
    Found <%= pluralize(@platforms.count, 'platform') %> when searching for: <%= params[:keywords] %>
</p>
<div class="columns is-multiline">
    <% @platforms.each do |p| %>
    <div class="column is-one-quarter">
        <div>
        <%= link_to "#{p.name}", p %>
        </div>
    </div>
    <% end %>
</div>

app/views/platforms/show.html.erb
<% content_for(:html_title) { raw@platform.name}%>
<br>
<h4 class="subtitle is-4">Games available on <%= @platform.name%>:</h4>

<div class="columns is-multiline">
    <% @platform.video_games.each do |vg| %>
        <div class="column is-one-quarter">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "300")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>

<a href="/platforms"><b>Return to all platforms</b></a>

app/views/publishers/index.html.erb
<% content_for(:html_title) {"Publishers"}%>
<p>All publishers:</p>
<br>
<div class="columns is-multiline">
    <% @publishers.each do |p| %>
    <div class="column is-one-quarter">
        <div>
        <%= link_to "#{p.name}", p %>
        </div>
    </div>
    <% end %>
</div>

app/views/publishers/search.html.erb
<p class="mb-5">
    Found <%= pluralize(@publishers.count, 'publisher') %> when searching for: <%= params[:keywords] %>
</p>

<div class="columns is-multiline">
    <% @publishers.each do |p| %>
    <div class="column is-one-quarter">
        <div>
        <%= link_to "#{p.name}", p %>
        </div>
    </div>
    <% end %>
</div>

app/views/publishers/show.html.erb
<% content_for(:html_title) {raw @publisher.name}%>
<br>
<h4 class="subtitle is-4">Games published by <%= @publisher.name%>:</h4>

<div class="columns is-multiline">
    <% @publisher.video_games.each do |vg| %>
        <div class="column is-one-quarter">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "300")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>

<a href="/publishers"><b>Return to all publishers</b></a>

app/views/video_games/index.html.erb
<p>All games:</p>
<br>
<div class="columns is-multiline">
    <% @video_games.each do |vg| %>
    <div class="column is-one-quarter">
        <div>
        <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "300")%>
        </div>
        <div>
        <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
        </div>
    </div>
    <% end %>
</div>

app/views/video_games/search.html.erb
<p class="mb-5">
    Found <%= pluralize(@video_games.count, 'video game') %> when searching for: <%= params[:keywords] %>
</p>
<div class="columns is-multiline">
    <% @video_games.each do |vg| %>
    <div class="column is-one-quarter">
        <div>
        <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "300")%>
        </div>
        <div>
        <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
        </div>
    </div>
    <% end %>
</div>

app/views/video_games/show.html.erb
<% content_for(:html_title) {raw @video_game.name}%>
<br>
<%= image_tag("video_games/#{@video_game.name.gsub(/\s+/, "")}.png", :alt => "#{@video_game.name}", :size => "500")%>
<p><strong>Developed by: </strong><%= link_to @video_game.developer.name, @video_game.developer %></p>
<p><strong>Published by: </strong><%= link_to @video_game.publisher.name, @video_game.publisher %></p>

<p><strong>Released for the: </strong><%= link_to @video_game.platform.name, @video_game.platform %> on <%= @video_game.release_date %>.</p>

<p><strong>Summary: </strong></p>
<p><%= @video_game.summary %></p>

<p><strong>Metacritic Score: </strong><%= @video_game.metacritic_score %></p>
<p><strong>User Score: </strong><%= @video_game.user_score %></p>

<p>Other games developed by <%= link_to @video_game.developer.name, @video_game.developer %>:</p>

<div class="columns is-multiline">
    <% @developer.video_games.each do |vg| %>
        <div class="column is-one-fourth">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "150")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>

<p>Other games published by <%= link_to @video_game.publisher.name, @video_game.publisher %>:</p>

<div class="columns is-multiline">
    <% @publisher.video_games.each do |vg| %>
        <div class="column is-one-fourth">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "150")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>

<p>Other games available on <%= link_to @video_game.platform.name, @video_game.platform %>:</p>

<div class="columns is-multiline">
    <% @platform.video_games.each do |vg| %>
        <div class="column is-one-fourth">
            <div>
                <%= image_tag("video_games/#{vg.name.gsub(/\s+/, "")}.png", :alt => "#{vg.name}", :size => "150")%>
            </div>
            <div>
                <%= link_to "#{vg.name} - (#{vg.platform.name} )", vg %>
            </div>
        </div>
    <% end %>
</div>


<a href="/video_games"><b>Return to all video games</b></a>